USE [msdb]
GO

/****** Object:  Job [DISPONIBILIDAD_CONVENIOS_2025_NEW]    Script Date: 3/12/2024 17:06:12 ******/
BEGIN TRANSACTION
DECLARE @ReturnCode INT
SELECT @ReturnCode = 0
/****** Object:  JobCategory [[Uncategorized (Local)]]    Script Date: 3/12/2024 17:06:12 ******/
IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N'[Uncategorized (Local)]' AND category_class=1)
BEGIN
EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N'JOB', @type=N'LOCAL', @name=N'[Uncategorized (Local)]'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback

END

DECLARE @jobId BINARY(16)
EXEC @ReturnCode =  msdb.dbo.sp_add_job @job_name=N'DISPONIBILIDAD_CONVENIOS_2025_NEW', 
		@enabled=1, 
		@notify_level_eventlog=0, 
		@notify_level_email=0, 
		@notify_level_netsend=0, 
		@notify_level_page=0, 
		@delete_level=0, 
		@description=N'No hay ninguna descripción.', 
		@category_name=N'[Uncategorized (Local)]', 
		@owner_login_name=N'MINSA\icastillo', @job_id = @jobId OUTPUT
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [BORRAR TABLA DISPO12FASE1]    Script Date: 3/12/2024 17:06:12 ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'BORRAR TABLA DISPO12FASE1', 
		@step_id=1, 
		@cmdexec_success_code=0, 
		@on_success_action=3, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'---- BORRAR TABLA -----
IF OBJECT_ID(''[DISPO12_CONVENIOS_2025_FASE3]'') IS NOT NULL
BEGIN
    DROP TABLE [DISPO12_CONVENIOS_2025_FASE3]
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END
----------------------------------------------
IF OBJECT_ID(''[DISPO12_CONVENIOS_2025_FASE2]'') IS NOT NULL
BEGIN
    DROP TABLE [DISPO12_CONVENIOS_2025_FASE2]
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END

----------------------------------------------
IF OBJECT_ID(''[INCLUSION_VITALES_2025]'') IS NOT NULL
BEGIN
    DROP TABLE [INCLUSION_VITALES_2025]
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END

', 
		@database_name=N'CONVENIOS_2025', 
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [GENERAR TABLA DE DISPONIBILIDAD FUSIONADA]    Script Date: 3/12/2024 17:06:12 ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'GENERAR TABLA DE DISPONIBILIDAD FUSIONADA', 
		@step_id=2, 
		@cmdexec_success_code=0, 
		@on_success_action=3, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'																																 ------ CREAR TABLA FASE_1---

SELECT * 
INTO DISPO12_CONVENIOS_2025_FASE2
FROM  [BACKUP_SISMED].[dbo].DISPO12_CONVENIOS_2024_FASE1;


---- GENERAR DISPOBILIDAD DE MEDICAMENTOS ESENCIALES FUSIONADOS---

SELECT E.[CODIGO_EJE],E.[NOMBRE_EJE],E.[CODDISA],E.[NOMDISA],P.[codigo_pre],E.[NOMBRE_PA_REPORTE]ESTABLEC,E.[ALMTIPO_COMPLETO],E.[ESTADO],E.[ALMTIPO],E.[codred],E.[red],E.[CATEGORIA],E.[ue],P.[CODIGO_SISMED_FUSIONADO],
M.[NOMBRE],M.[TIPO],M.[PETITORIO],M.[ESTRATEGIC],M.[SUB_TIPO],M.[NOM_SUB_TIPO],M.[CODIGO_ATC],
M.[FORMA_FARM]
	
	,[M1tot]
	,[M2tot]
	,[M3tot]
	,[M4tot]
	,[M5tot]
	,[M6tot]
	,[M7tot]
	,[M8tot]
	,[M9tot]
	,[M10tot]
	,[M11tot]
	,[M12tot]
	,[con_sismed]	 	
	,[stk_sismed] 
	,[NMESES]
	,[CPA]
	,[DISPO]
	,[INDICADOR]	
	,MESANO
    ,E.[CODUE_MEF],E.[UE_MEF],E.[DPTO]	 
INTO DISPO12_CONVENIOS_2025_FASE3
FROM  [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE2 P
LEFT JOIN [BACKUP_SISMED].[dbo].[ESTABLEC] E  ON P.codigo_pre=E.CODIGO_PRE
	COLLATE Modern_Spanish_CI_AS	
	LEFT JOIN [BACKUP_SISMED].[dbo].[MEDICA] M  ON P.[CODIGO_SISMED_FUSIONADO]=M.CODIGO_MED
	COLLATE Modern_Spanish_CI_AS
	WHERE  E.[ESTADO]=''A'' AND E.TIPO_IPRES NOT IN (''CME'') AND M.TIPO=''M''AND E.[ALMTIPO_COMPLETO] IN(''INSTITUTO'',''HOSPITAL'',''C.S.'',''P.S.'') AND M.PETITORIO=''P'' AND M.ESTRATEGIC NOT IN (''SC'') AND P.[CODIGO_SISMED_FUSIONADO] NOT IN (''03883'',''03884'',''04162'',''05808'',''05809'',''08139'',''08140'',''22291'',''29964'',''34847'',''99998'',''99999'',''26953''
,''31744''
,''46456''
,''08020''
,''27817''
,''46007''
,''46008''
,''41234''
,''46727''
,''08138''
,''41434''
,''44221''
,''44222''
,''44529''
,''44648''
,''52635''
,''52636'')
GO
------------SELECCION DE MEDICAMENTOS VITALES SIN ROTACION-------

SELECT D.* 
INTO  INCLUSION_VITALES_2025
FROM DISPO12_CONVENIOS_2025_FASE3 D
INNER JOIN [CONVENIOS_2025].[dbo].VITALES_2 V ON D.CODIGO_SISMED_FUSIONADO=V.CODIGO_MED_V 
WHERE D.INDICADOR   IN (''SINROTACION'') ;


------------ ELIMINAR REGISTROS SIN ROTACION QUE NO SON VITALES-----------------

DELETE F
FROM [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE3 F 
LEFT JOIN INCLUSION_VITALES_2025 P  
    ON F.codigo_pre = P.CODIGO_PRE 
    AND F.CODIGO_SISMED_FUSIONADO = P.CODIGO_SISMED_FUSIONADO 
    AND F.INDICADOR = P.INDICADOR
WHERE F.INDICADOR IN (''SINROTACION'') AND P.CODIGO_PRE IS NULL;


---- INSERTAR LOS REGISTROS SIN ROTACION VITALES------
--INSERT INTO [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE3
--SELECT * FROM [CONVENIOS_2025].[dbo].INCLUSION_VITALES_2025 ; 

------- ELIMINAR PRODUCTOS DE LISTA DE CANCER MENOS LOS ESPECIALIZADOS--------------

DELETE F
FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3] F 
INNER JOIN   LISTA_CANCER P  ON F.CODIGO_SISMED_FUSIONADO=P.CODIGO_MED  
WHERE F.CODIGO_PRE NOT IN (SELECT CODIGO_PRE FROM IPRESS_ESTRATEGIAS WHERE ESTRATEGIA=''CANCER'' );
GO


------- ELIMINAR PRODUCTOS DE LISTA DE OCULAR MENOS LOS ESPECIALIZADOS--------------

DELETE F
FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3] F 
INNER JOIN   LISTA_CANCER P  ON F.CODIGO_SISMED_FUSIONADO=P.CODIGO_MED  
WHERE F.CODIGO_PRE NOT IN (SELECT CODIGO_PRE FROM IPRESS_ESTRATEGIAS WHERE ESTRATEGIA=''OCULAR'' );
GO

-------------------------------ELIMINAR PRODUCTOS  ------------------
  DELETE FROM  DISPO12_CONVENIOS_2025_FASE3
  WHERE  CODIGO_SISMED_FUSIONADO IN (''04364'',''04365'',''04458'',''04910'') AND  ALMTIPO IN (''C'',''P'')

  DELETE FROM  DISPO12_CONVENIOS_2025_FASE3
  WHERE CODIGO_PRE=''06210'' AND  CODIGO_SISMED_FUSIONADO IN (''02848'') 

  DELETE FROM  DISPO12_CONVENIOS_2025_FASE3
  WHERE CODIGO_PRE=''06211'' AND  CODIGO_SISMED_FUSIONADO IN (''03536'',''18511'')
  
  DELETE FROM  DISPO12_CONVENIOS_2025_FASE3
  WHERE ALMTIPO IN (''H'',''I'') AND CODIGO_SISMED_FUSIONADO IN (''39705'')



------- ELIMINAR PRODUCTOS DE IPRESS DE LISTA DE IPRESS--------------

DELETE F
FROM [dbo].DISPO12_CONVENIOS_2025_FASE3 F 
INNER JOIN EXCLUIR_IPRESS P  
ON F.codigo_pre=P.CODIGO_PRE AND F.CODIGO_SISMED_FUSIONADO=P.CODIGO_MED ; 
GO


------- ELIMINAR PRODUCTOS POR DIRESAS TODO EL AÑO--------------

DELETE F
FROM [dbo].DISPO12_CONVENIOS_2025_FASE3 F 
INNER JOIN EXCLUIR_DISAS P  
ON F.CODDISA=P.CODDISA AND F.CODIGO_SISMED_FUSIONADO=P.CODIGO_MED AND F.ALMTIPO_COMPLETO IN (''C.S.'',''P.S.'') ; 
GO

------- ELIMINAR PRODUCTOS DE IPRESS DE LISTA DE IPRESS Y POR MES --------------

DELETE F
FROM [dbo].DISPO12_CONVENIOS_2025_FASE3 F 
INNER JOIN EXCLUIR_IPRESS_X_MESES P  
ON F.codigo_pre=P.CODIGO_PRE AND F.CODIGO_SISMED_FUSIONADO=P.CODIGO_MED AND F.MESANO=P.PERIODO ; 
GO

------- ELIMINAR PRODUCTOS DE LIMA DE EXCLUSION--------------

DELETE F
FROM [dbo].DISPO12_CONVENIOS_2025_FASE3 F 
INNER JOIN LISTADO_EXCLUIR P  
ON F.CODIGO_SISMED_FUSIONADO = P.CODIGO_MED ; 
GO


------- ELIMINAR PRODUCTOS DE LIMA DE EXCLUSION POR MESES--------------

DELETE F
FROM [dbo].DISPO12_CONVENIOS_2025_FASE3 F 
INNER JOIN [EXCLUIR_DISAS_X_MESES]P  
ON F.CODIGO_SISMED_FUSIONADO = P.CODIGO_MED AND F.MESANO=P.PERIODO ; 
GO

------- ELIMINAR PRODUCTOS APROBADOS EN EL FORMULARIO DE DETERMINACION --------------

DELETE F
FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3] F 
 INNER JOIN listado_detprod_2025_fi L on F.codigo_pre=L.codpre_ and F.CODIGO_SISMED_FUSIONADO=L.[medcod_id] 
 WHERE L.[estado_registro]=''APRB'';
GO



---- ACTUALUALIZAR LISTA A 1 MES DE DISPONIBILIDAD-------------

 UPDATE [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE3 
  SET DISPO12_CONVENIOS_2025_FASE3.INDICADOR=''NORMOSTOCK''
  FROM [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE3 F
  INNER JOIN [BACKUP_SISMED].[dbo].[MEDICA_1MES] A
  ON F.CODIGO_SISMED_FUSIONADO=A.CODIGO_MED
  WHERE (F.DISPO >=1 AND F.DISPO <2 ) ;
GO

---- ACTUALUALIZAR SINCONSUMO A DESABASTECIDOS DISPONIBILIDAD-------------

 UPDATE [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE3 
 SET DISPO12_CONVENIOS_2025_FASE3.INDICADOR=''DESABASTECIDO''
 FROM [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE3 F
 WHERE F.INDICADOR=''SINCONSUMO'';
 GO

----- ACTUALUALIZAR PRODUCTOS DE SOBRESTOCK A NORMOSTOCK SEGUN LISTA POR UNIDAD EJECUTORA-------------

 UPDATE [CONVENIOS_2025].[dbo].[DISPO12_CONVENIOS_2025_FASE3] 
 SET [DISPO12_CONVENIOS_2025_FASE3].INDICADOR=''NORMOSTOCK''
 FROM [CONVENIOS_2025].[dbo].[DISPO12_CONVENIOS_2025_FASE3] F
 INNER JOIN [CONVENIOS_2025].[dbo].[listado_detprod_2025_unidadejecutora] A
 ON F.CODUE_MEF=A.[codigo_mef] AND F.DISPO > 6 and F.DISPO <= A.maximo_valor_normostock
 WHERE (A.maximo_valor_normostock <>6);


----------- ELIMINAR TABLAS DE APOYO----
DROP  TABLE [CONVENIOS_2025].[dbo].DISPO12_CONVENIOS_2025_FASE2;
DROP  TABLE [CONVENIOS_2025].[dbo].INCLUSION_VITALES_2025;', 
		@database_name=N'CONVENIOS_2025', 
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
/****** Object:  Step [GENERAR REPORTE DE DISPONIBILIDAD POR UE-REGIONES-REDES]    Script Date: 3/12/2024 17:06:12 ******/
EXEC @ReturnCode = msdb.dbo.sp_add_jobstep @job_id=@jobId, @step_name=N'GENERAR REPORTE DE DISPONIBILIDAD POR UE-REGIONES-REDES', 
		@step_id=3, 
		@cmdexec_success_code=0, 
		@on_success_action=1, 
		@on_success_step_id=0, 
		@on_fail_action=2, 
		@on_fail_step_id=0, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'TSQL', 
		@command=N'USE [CONVENIOS_2025]
GO

IF OBJECT_ID(''XXXX_DISPO_EJECUTORAS_CONSOLIDA_2_MES_2025'') IS NOT NULL
BEGIN
    DROP TABLE XXXX_DISPO_EJECUTORAS_CONSOLIDA_2_MES_2025;
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END

IF OBJECT_ID(''XXXX_DISPO_REGIONES_CONSOLIDA_2_MES_2025'') IS NOT NULL
BEGIN
    DROP TABLE XXXX_DISPO_REGIONES_CONSOLIDA_2_MES_2025;
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END

IF OBJECT_ID(''XXXX_DISPO_REDES_CONSOLIDA_2_MES_2025'') IS NOT NULL
BEGIN
    DROP TABLE XXXX_DISPO_REDES_CONSOLIDA_2_MES_2025;
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END

IF OBJECT_ID(''XXXX_DISPO_REGIONES_CONSOLIDA_2_MES_DETALLE_CONSOLIDO_2025'') IS NOT NULL
BEGIN
    DROP TABLE XXXX_DISPO_REGIONES_CONSOLIDA_2_MES_DETALLE_CONSOLIDO_2025;
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END

IF OBJECT_ID(''XXXX_DISPO_REDES_CONSOLIDA_2_MES_DETALLE_CONSOLIDO_2025'') IS NOT NULL
BEGIN
    DROP TABLE XXXX_DISPO_REDES_CONSOLIDA_2_MES_DETALLE_CONSOLIDO_2025;
    PRINT ''La tabla ha sido eliminada.'';
END
ELSE
BEGIN
    PRINT ''La tabla no existe.'';
END


---------DISPONIBILIDAD A 1 MES UNIDADES EJECUTORAS----------
  	SELECT *
	INTO XXXX_DISPO_EJECUTORAS_CONSOLIDA_2_MES_2025	
	FROM
      (	
			SELECT  F.[CODIGO_EJE],F.[NOMBRE_EJE],F.[CODDISA], F.[NOMDISA],F.[CODIGO_PRE], F.[ESTABLEC],F.[ALMTIPO_COMPLETO],F.[DPTO],F.[CODUE_MEF],F.[UE_MEF],F.UE,F.SOBRESTOCK, F.NORMOSTOCK,F.SINROTACION, F.SUBSTOCK, F.DESABASTECIDO, F.TOTAL, ISNULL(CONVERT(FLOAT,F.DIPO),0) AS DISPO,F.MESANO
	
	
		FROM
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE], [ESTABLEC],UE,MESANO,[ALMTIPO_COMPLETO]      
			,[DPTO]
           ,[CODUE_MEF]
           ,[UE_MEF] ,   
			ISNULL([SOBRESTOCK],0) [SOBRESTOCK],
			ISNULL([NORMOSTOCK],0) [NORMOSTOCK],
			ISNULL([SUBSTOCK],0) [SUBSTOCK], 
			ISNULL([DESABASTECIDO],0) [DESABASTECIDO],
			ISNULL([SINROTACION],0) [SINROTACION],
			ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0)  [TOTAL],
			CASE WHEN ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0)+ISNULL([SINROTACION],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) +ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ISNULL([DESABASTECIDO],0)),0.0),4) END DIPO,
			CASE WHEN ISNULL(SUM (ISNULL([SUBSTOCK],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SUBSTOCK],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0.0),4) END SUBSTOC,
			CASE WHEN ISNULL(SUM (ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([DESABASTECIDO],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0) +ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0.0),4) END DESABASTECI
			
		FROM 
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE],[ESTABLEC],[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO, Indicador FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3]
            WHERE  ESTADO=''A''  --------------- and [ALMTIPO_COMPLETO] IN(''INSTITUTO'',''HOSPITAL'')  -----------
		) T

		PIVOT ( COUNT (T.indicador) FOR T.indicador IN ([SOBRESTOCK], [NORMOSTOCK], [SUBSTOCK],[SINROTACION], [DESABASTECIDO], [TOTAL], [DIPO] )) AS PIVOTTABLE
				GROUP BY  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE],ESTABLEC,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO,[SOBRESTOCK], [NORMOSTOCK], [SUBSTOCK],[SINROTACION],[DESABASTECIDO], [TOTAL]
		
		)F 

	) G  

	---SELECT * FROM  [DISPO12_CONVENIOS_2025_FASE3]

---------DISPONIBILIDAD A 1 MES REGIONES NIVEL NACIONAL ----------

SELECT [CODIGO_EJE],[NOMBRE_EJE],CODDISA, NOMDISA,[DPTO],[CODUE_MEF],[UE_MEF],AVG(DISPO)AS PROMEDIO,MESANO 
INTO XXXX_DISPO_REGIONES_CONSOLIDA_2_MES_2025
  FROM
	(
	SELECT *
	
	FROM
	(	
		SELECT F.[CODIGO_EJE],F.[NOMBRE_EJE],F.[CODDISA], F.[NOMDISA],F.[CODIGO_PRE], F.[ESTABLEC],F.[ALMTIPO_COMPLETO],F.UE,F.[DPTO],F.[CODUE_MEF],F.[UE_MEF], F.SOBRESTOCK, F.NORMOSTOCK, F.SINROTACION, F.SUBSTOCK, F.DESABASTECIDO, F.TOTAL, ISNULL(CONVERT(FLOAT,F.DIPO),0) AS DISPO,F.MESANO
	
	
		FROM
		(
			SELECT [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE], [ESTABLEC],[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO,
			ISNULL([SOBRESTOCK],0) [SOBRESTOCK],
			ISNULL([NORMOSTOCK],0) [NORMOSTOCK],
			ISNULL([SUBSTOCK],0) [SUBSTOCK], 
			ISNULL([DESABASTECIDO],0) [DESABASTECIDO],
			ISNULL([SINROTACION],0) [SINROTACION],
			ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0)  [TOTAL],
			CASE WHEN ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0)+ISNULL([SINROTACION],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) +ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ISNULL([DESABASTECIDO],0)),0.0),4) END DIPO,
			CASE WHEN ISNULL(SUM (ISNULL([SUBSTOCK],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SUBSTOCK],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0.0),4) END SUBSTOC,
			CASE WHEN ISNULL(SUM (ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([DESABASTECIDO],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0) +ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0.0),4) END DESABASTECI
			
		FROM 
		(
			SELECT [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE], [ESTABLEC],[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO, Indicador FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3]
            WHERE [ALMTIPO_COMPLETO] IN(''C.S.'',''P.S.'',''INSTITUTO'',''HOSPITAL'') AND UE NOT IN (''U'')AND ESTADO=''A''
			
		) T

		PIVOT ( COUNT (T.indicador) FOR T.indicador IN ([SOBRESTOCK], [NORMOSTOCK],[SINROTACION], [SUBSTOCK], [DESABASTECIDO], [TOTAL], [DIPO] )) AS PIVOTTABLE
				GROUP BY [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE],ESTABLEC,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO,[SOBRESTOCK], [NORMOSTOCK],[SINROTACION], [SUBSTOCK], [DESABASTECIDO], [TOTAL]
		
		)F    
	)G
)X GROUP BY [CODIGO_EJE],[NOMBRE_EJE],CODDISA, NOMDISA,[DPTO],[CODUE_MEF],[UE_MEF],MESANO



---------DISPONIBILIDAD A 1 MES REDES NIVEL NACIONAL ----------

SELECT  [CODIGO_EJE],[NOMBRE_EJE],CODDISA, NOMDISA,CODRED,RED,UE,[DPTO],[CODUE_MEF],[UE_MEF], AVG(DISPO) AS PROMEDIO,MESANO 
INTO XXXX_DISPO_REDES_CONSOLIDA_2_MES_2025
	FROM
		(

		SELECT *
		
		FROM
		(	
		SELECT  F.[CODIGO_EJE],F.[NOMBRE_EJE],F.[CODDISA], F.[NOMDISA],CODIGO_PRE,ESTABLEC,F.[CODRED], F.[RED],F.[ALMTIPO_COMPLETO],F.[DPTO],F.[CODUE_MEF],F.[UE_MEF] ,F.UE, F.SOBRESTOCK, F.NORMOSTOCK,F.SINROTACION, F.SUBSTOCK, F.DESABASTECIDO, F.TOTAL,ISNULL(CONVERT(FLOAT,F.DIPO),0) AS DISPO,f.mesano
	
		FROM
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],CODIGO_PRE,ESTABLEC,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF]
           ,[UE_MEF] ,codred,RED,UE,mesano,
			ISNULL([SOBRESTOCK],0) [SOBRESTOCK],
			ISNULL([NORMOSTOCK],0) [NORMOSTOCK],
			ISNULL([SUBSTOCK],0) [SUBSTOCK], 
			ISNULL([DESABASTECIDO],0) [DESABASTECIDO],
			ISNULL([SINROTACION],0) [SINROTACION],
			ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0)  [TOTAL],
			CASE WHEN ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0)+ISNULL([SINROTACION],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) +ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ISNULL([DESABASTECIDO],0)),0.0),4) END DIPO,
			CASE WHEN ISNULL(SUM (ISNULL([SUBSTOCK],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SUBSTOCK],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0.0),4) END SUBSTOC,
			CASE WHEN ISNULL(SUM (ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([DESABASTECIDO],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0) +ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0.0),4) END DESABASTECI
			
		FROM 
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],codigo_pre,ESTABLEC,codred,RED,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF] ,UE,mesano,Indicador FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3]
            WHERE [ALMTIPO_COMPLETO] IN(''INSTITUTO'',''HOSPITAL'',''C.S.'',''P.S.'') AND UE NOT IN(''U'') AND ESTADO=''A''
		) T

		PIVOT ( COUNT (T.indicador) FOR T.indicador IN ([SOBRESTOCK], [NORMOSTOCK],[SINROTACION], [SUBSTOCK], [DESABASTECIDO], [TOTAL], [DIPO] )) AS PIVOTTABLE
				GROUP BY  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],CODIGO_PRE,ESTABLEC,codred,RED,UE,mesano,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF] ,[SOBRESTOCK], [NORMOSTOCK],[SINROTACION], [SUBSTOCK], [DESABASTECIDO], [TOTAL]
		
		)F 
	 )G
	
)X GROUP BY  [CODIGO_EJE],[NOMBRE_EJE],CODDISA, NOMDISA,CODRED,RED,UE,[DPTO],[CODUE_MEF],[UE_MEF] ,MESANO 

----- GENERAR DISPONIBILIDAD DETALLADA REGIONES-------------
		SELECT  F.[CODIGO_EJE],F.[NOMBRE_EJE],F.[CODDISA], F.[NOMDISA],F.[CODIGO_PRE], F.[ESTABLEC],F.[ALMTIPO_COMPLETO],F.[DPTO],F.[CODUE_MEF],F.[UE_MEF],F.UE,F.SOBRESTOCK, F.NORMOSTOCK,F.SINROTACION, F.SUBSTOCK, F.DESABASTECIDO, F.TOTAL, ISNULL(CONVERT(FLOAT,F.DIPO),0) AS DISPO,F.MESANO
		INTO XXXX_DISPO_REGIONES_CONSOLIDA_2_MES_DETALLE_CONSOLIDO_2025
	
		FROM
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE], [ESTABLEC],UE,MESANO,[ALMTIPO_COMPLETO]      
			,[DPTO]
           ,[CODUE_MEF]
           ,[UE_MEF] ,   
			ISNULL([SOBRESTOCK],0) [SOBRESTOCK],
			ISNULL([NORMOSTOCK],0) [NORMOSTOCK],
			ISNULL([SUBSTOCK],0) [SUBSTOCK], 
			ISNULL([DESABASTECIDO],0) [DESABASTECIDO],
			ISNULL([SINROTACION],0) [SINROTACION],
			ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0)  [TOTAL],
			CASE WHEN ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0)+ISNULL([SINROTACION],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) +ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ISNULL([DESABASTECIDO],0)),0.0),4) END DIPO,
			CASE WHEN ISNULL(SUM (ISNULL([SUBSTOCK],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SUBSTOCK],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0.0),4) END SUBSTOC,
			CASE WHEN ISNULL(SUM (ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([DESABASTECIDO],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0) +ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0.0),4) END DESABASTECI
			
		FROM 
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE],[ESTABLEC],[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO, Indicador FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3]
          WHERE [ALMTIPO_COMPLETO] IN(''INSTITUTO'',''HOSPITAL'',''C.S.'',''P.S.'') AND UE NOT IN(''U'') AND ESTADO=''A''

		) T

		PIVOT ( COUNT (T.indicador) FOR T.indicador IN ([SOBRESTOCK], [NORMOSTOCK], [SUBSTOCK],[SINROTACION], [DESABASTECIDO], [TOTAL], [DIPO] )) AS PIVOTTABLE
				GROUP BY  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],[CODIGO_PRE],ESTABLEC,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF],UE,MESANO,[SOBRESTOCK], [NORMOSTOCK], [SUBSTOCK],[SINROTACION],[DESABASTECIDO], [TOTAL]
		
		)F 

----- GENERAR DISPONIBILIDAD DETALLADA POR REDES -------------

	SELECT *
	INTO XXXX_DISPO_REDES_CONSOLIDA_2_MES_DETALLE_CONSOLIDO_2025 
		FROM
		(	
			SELECT  F.[CODIGO_EJE],F.[NOMBRE_EJE],F.[CODDISA], F.[NOMDISA],CODIGO_PRE,ESTABLEC,F.[CODRED], F.[RED],F.[ALMTIPO_COMPLETO],F.[DPTO],F.[CODUE_MEF],F.[UE_MEF] ,F.UE, F.SOBRESTOCK, F.NORMOSTOCK,F.SINROTACION, F.SUBSTOCK, F.DESABASTECIDO, F.TOTAL,ISNULL(CONVERT(FLOAT,F.DIPO),0) AS DISPO,f.mesano
	
		FROM
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],CODIGO_PRE,ESTABLEC,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF]
           ,[UE_MEF] ,codred,RED,UE,mesano,
			ISNULL([SOBRESTOCK],0) [SOBRESTOCK],
			ISNULL([NORMOSTOCK],0) [NORMOSTOCK],
			ISNULL([SUBSTOCK],0) [SUBSTOCK], 
			ISNULL([DESABASTECIDO],0) [DESABASTECIDO],
			ISNULL([SINROTACION],0) [SINROTACION],
			ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0)  [TOTAL],
			CASE WHEN ISNULL(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0)+ISNULL([SINROTACION],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) +ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0)+ISNULL([DESABASTECIDO],0)),0.0),4) END DIPO,
			CASE WHEN ISNULL(SUM (ISNULL([SUBSTOCK],0)),0) > 0
			THEN ROUND(SUM (ISNULL([SUBSTOCK],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0)+ISNULL([SINROTACION],0) + ISNULL([DESABASTECIDO],0)),0.0),4) END SUBSTOC,
			CASE WHEN ISNULL(SUM (ISNULL([DESABASTECIDO],0)),0) > 0
			THEN ROUND(SUM (ISNULL([DESABASTECIDO],0))*100.0/NULLIF(SUM (ISNULL([SOBRESTOCK],0) + ISNULL([NORMOSTOCK],0) + ISNULL([SUBSTOCK],0) +ISNULL([SINROTACION],0)+ ISNULL([DESABASTECIDO],0)),0.0),4) END DESABASTECI
			
		FROM 
		(
			SELECT  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],codigo_pre,ESTABLEC,codred,RED,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF] ,UE,mesano,Indicador FROM [dbo].[DISPO12_CONVENIOS_2025_FASE3]
            WHERE [ALMTIPO_COMPLETO] IN(''INSTITUTO'',''HOSPITAL'',''C.S.'',''P.S.'') AND UE NOT IN(''U'') AND ESTADO=''A''

		) T

		PIVOT ( COUNT (T.indicador) FOR T.indicador IN ([SOBRESTOCK], [NORMOSTOCK],[SINROTACION], [SUBSTOCK], [DESABASTECIDO], [TOTAL], [DIPO] )) AS PIVOTTABLE
				GROUP BY  [CODIGO_EJE],[NOMBRE_EJE],[CODDISA], [NOMDISA],CODIGO_PRE,ESTABLEC,codred,RED,UE,mesano,[ALMTIPO_COMPLETO],[DPTO],[CODUE_MEF],[UE_MEF] ,[SOBRESTOCK], [NORMOSTOCK],[SINROTACION], [SUBSTOCK], [DESABASTECIDO], [TOTAL]
		
		)F 
	 )G
GO

', 
		@database_name=N'CONVENIOS_2025', 
		@flags=0
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_update_job @job_id = @jobId, @start_step_id = 1
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
EXEC @ReturnCode = msdb.dbo.sp_add_jobserver @job_id = @jobId, @server_name = N'(local)'
IF (@@ERROR <> 0 OR @ReturnCode <> 0) GOTO QuitWithRollback
COMMIT TRANSACTION
GOTO EndSave
QuitWithRollback:
    IF (@@TRANCOUNT > 0) ROLLBACK TRANSACTION
EndSave:
GO


